SemanticTokens:
  DisabledKinds: [Variable, LocalVariable, StaticField, Parameter, StaticMethod, Function, Method, Field, Class, Interface, Enum, EnumConstant, Type, Typedef, Primitive, TemplateParameter, Namespace, Macro, Modifier, Operator, Bracket, Label, Unknown, Concept]
  DisabledModifiers: []
