#! /bin/bash
# HooK
pt=$(pwd)
echo $pt > /tmp/sdlhook
pt=$(echo $pt |awk -F'/' '{ for (i=1; i<=NF-1; i++) { if (length($i) > 1) { printf "%s/", substr($i, 1, 1); } else { printf "%s/", $i; } } print $NF }')
echo "H;$pt" > /tmp/dwm.fifo
