#!/bin/bash

if [[ "$1" != "-t" ]]; then
    read -r content
    echo "$content" > /tmp/sdcmd
    tmux display-panes -d 0 "run-shell \"$0 -t %% $@\""
    exit 0
fi

while [ "$#" -gt 0 ]; do
    case "$1" in
        -t)
            shift
            target=$1
            shift
            ;;
        -N)
            went=1
            shift
            ;;
        *)
            echo "unknown arg: $1"
            shift
            ;;
    esac
done

if [[ "$TMUX_PANE" == "$target" ]]; then
    exit 1
fi
if [[ "$went" == "1" ]]; then
    tmux select-pane -t $target
fi

in=$(cat /tmp/sdcmd)
(sleep 0.1 && eval "tmux send -t $target $in" &)
