#!/bin/bash

read -r content
current_pane=$TMUX_PANE
tmux display-panes -d 0
target_pane=$(tmux display-message -p '#{pane_id}')
tmux select-pane -t $current_pane
if [[ "$current_pane" == "$target_pane" ]]; then
    exit 1
fi
(sleep 0.1 && eval "tmux send -t $target_pane $content" &)
