#!/bin/bash

read content
current_pane=$TMUX_PANE
tmux display-panes -d 0
target_pane=$(tmux display-message -p '#{pane_id}')
tmux select-pane -t $current_pane
(sleep 0.1 && tmux send -t $target_pane $content &)
