#!/bin/bash
if [ -f "/tmp/waitforrunbeast" ];then
    exit
fi
touch /tmp/waitforrunbeast

if [ -f "/tmp/beast.lock" ];then # off
    if [ -f "$HOME/.scripts/boff.sh" ];then
        $1
    fi
    rm /tmp/beast.lock
    if [[ $? == 0 ]] then
        echo "B;0" > /tmp/dwm.fifo
    fi
else # on
    touch /tmp/beast.lock
    echo "B;1" > /tmp/dwm.fifo
    if [ -f "$HOME/.scripts/bon.sh" ];then
        $2
    fi
    echo "B;2" > /tmp/dwm.fifo
fi

rm /tmp/waitforrunbeast
