#!/bin/bash
result=`xrandr |grep " connected " |cut -d " " -f 1`
readarray -t dps <<< $result
result=`xrandr --verbose |grep Gamma |sed 's/\s\+/|/g' |cut -d '|' -f 3`
readarray -t rgb <<< $result
if [[ "${rgb[0]}" != "1.0:1.0:1.0" ]]; then
    for dp in "${dps[@]}"; do
        xrandr --output $dp --gamma 1
    done
else
    for dp in "${dps[@]}"; do
        xrandr --output $dp --brightness 0.7 --gamma 0.9:0.6:0.3
    done
fi
