#!/bin/bash
id=`xinput|grep TouchPad|awk '{x=$6;split(x,arr,"=");print arr[2];}'`
if test "$id" == ""; then
    id=`xinput|grep TouchPad|awk '{x=$5;split(x,arr,"=");print arr[2];}'`
fi
flag=`xinput list-props $id|grep "Device Enabled"|cut -d : -f 2|awk '{print $1}'`
if [ $flag == 0 ]
then
    xinput enable $id
    echo 1 > /tmp/statusBar/touchpad
else
    xinput disable $id
    echo 0 > /tmp/statusBar/touchpad
fi
