#!/bin/bash

if test "$1" = "up"; then
    amixer sset Master 3%+ unmute &> /dev/null
elif test "$1" = "down"; then
    amixer sset Master 3%- unmute &> /dev/null
else
    amixer sset Master toggle &> /dev/null
    volstat=$(amixer get Master |grep '\[off\]')
fi

if [ "$volstat" != "" ]; then
    echo "V;0" > /tmp/dwm.fifo
else
    amixer get Master |awk -F '[]%[]' 'END{printf "V;%d\n", $2}' > /tmp/dwm.fifo
fi
