#!/usr/bin/env python
import sys

pwd = sys.argv[1]
mx = int(sys.argv[2])
length = len(pwd)
if length <= mx:
    print(pwd)
else:
    folders = pwd.split("/")
    idx = 1
    while length > mx:
        try:
            if len(folders[idx]) > 1:
                length -= len(folders[idx]) - 2
                folders[idx] = folders[idx][0] + ";"
            idx += 1
        except:
            break
    print("/".join(folders))
